# Generated by Django 3.1.2 on 2022-01-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0003_auto_20220113_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tigID', models.IntegerField(default=-1)),
                ('transactionPrice', models.FloatField(default=0)),
                ('quantite', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ('tigID',),
            },
        ),
        migrations.AlterField(
            model_name='produitstock',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
