# Generated by Django 3.1.2 on 2022-01-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytig', '0004_auto_20220116_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='produittransaction',
            name='type',
            field=models.CharField(default='mer', max_length=20),
        ),
    ]
